export const product = [
  {
    id: 1,
    code: "PD-00001",
    name: "Sofa CHESTER",
    material: "Pine-Wood-Plywood-Rubber-Wood-84%-Polyester-16%PU",
    source: "Việt Nam",
    guarantee: 12,
    size: "L203xW93xH80",
    description: null,
    status: "active",
    productType: {
      id: 61,
      idRooms: null,
      code: "PT-00007",
      name: "Sofa",
      image: "so-fa.jpg",
      rooms: null,
      status: "active",
    },
    productDetail: [
      {
        id: 1,
        code: "PDT-00001",
        colors: "Cognac",
        numberStock: 198,
        productPrice: 17900000.0,
        realPrice: 17900000.0,
        status: "active",
        product: null,
        images: [
          {
            id: 1,
            code: "IM-00001",
            link: "chester_sofa_baya_5298.jpg",
            productDetail: null,
          },
          {
            id: 11,
            code: "IM-00002",
            link: "chester_sofa_baya_5298_1.jpg",
            productDetail: null,
          },
          {
            id: 21,
            code: "IM-00003",
            link: "chester_sofa_baya_5298_2.jpg",
            productDetail: null,
          },
          {
            id: 31,
            code: "IM-00004",
            link: "chester_sofa_baya_5298_3.jpg",
            productDetail: null,
          },
          {
            id: 41,
            code: "IM-00005",
            link: "chester_sofa_baya_5298_4.jpg",
            productDetail: null,
          },
        ],
      },
    ],
  },
  {
    id: 11,
    code: "PD-00002",
    name: "Sofa giường có hộc SILVA",
    material: "Vải tổng hợp",
    source: "Trung Quốc",
    guarantee: 12,
    size: "L215xW133xH83",
    description: null,
    status: "active",
    productType: {
      id: 61,
      idRooms: null,
      code: "PT-00007",
      name: "Sofa",
      image: "so-fa.jpg",
      rooms: null,
      status: "active",
    },
    productDetail: [
      {
        id: 11,
        code: "PDT-00002",
        colors: "Xám",
        numberStock: 200,
        productPrice: 10990000.0,
        realPrice: 10990000.0,
        status: "active",
        product: null,
        images: [
          {
            id: 51,
            code: "IM-00006",
            link: "silva_sofa_bed_with_storage_baya_5249.jpg",
            productDetail: null,
          },
          {
            id: 61,
            code: "IM-00007",
            link: "silva_sofa_bed_with_storage_baya_5249.jpg_1",
            productDetail: null,
          },
          {
            id: 71,
            code: "IM-00008",
            link: "silva_sofa_bed_with_storage_baya_5249.jpg_2",
            productDetail: null,
          },
          {
            id: 81,
            code: "IM-00009",
            link: "silva_sofa_bed_with_storage_baya_5249.jpg_3",
            productDetail: null,
          },
          {
            id: 91,
            code: "IM-00010",
            link: "silva_sofa_bed_with_storage_baya_5249.jpg_4",
            productDetail: null,
          },
          {
            id: 101,
            code: "IM-00011",
            link: "silva_sofa_bed_with_storage_baya_5249.jpg_5",
            productDetail: null,
          },
          {
            id: 111,
            code: "IM-000012",
            link: "silva_sofa_bed_with_storage_baya_5249.jpg_6",
            productDetail: null,
          },
        ],
      },
    ],
  },
  {
    id: 21,
    code: "PD-00003",
    name: "Sofa giường GINA",
    material: "Rubber-Wood-Plywood-100%-Polyester",
    source: "Việt Nam",
    guarantee: 12,
    size: "L180xW96xH77",
    description: null,
    status: "active",
    productType: {
      id: 61,
      idRooms: null,
      code: "PT-00007",
      name: "Sofa",
      image: "so-fa.jpg",
      rooms: null,
      status: "active",
    },
    productDetail: [
      {
        id: 21,
        code: "PDT-00003",
        colors: "Hồng nhạt",
        numberStock: 200,
        productPrice: 3990000.0,
        realPrice: 3990000.0,
        status: "active",
        product: null,
        images: [
          {
            id: 121,
            code: "IM-00013",
            link: "gina_sofa_bed_baya_5231.jpg",
            productDetail: null,
          },
          {
            id: 131,
            code: "IM-00014",
            link: "gina_sofa_bed_baya_5231_1.jpg",
            productDetail: null,
          },
          {
            id: 141,
            code: "IM-00015",
            link: "gina_sofa_bed_baya_5231_3.jpg",
            productDetail: null,
          },
          {
            id: 151,
            code: "IM-00016",
            link: "gina_sofa_bed_baya_5231_4.jpg",
            productDetail: null,
          },
          {
            id: 161,
            code: "IM-00017",
            link: "gina_sofa_bed_baya_5231_5.jpg",
            productDetail: null,
          },
          {
            id: 171,
            code: "IM-00018",
            link: "gina_sofa_bed_baya_5231_6.jpg",
            productDetail: null,
          },
        ],
      },
    ],
  },
  {
    id: 31,
    code: "PD-00004",
    name: "Sofa kèm ghế nằm NARBONNE",
    material: "Vải tổng hợp",
    source: "Việt Nam",
    guarantee: 12,
    size: "D92/151xW247xH93",
    description: null,
    status: "active",
    productType: {
      id: 61,
      idRooms: null,
      code: "PT-00007",
      name: "Sofa",
      image: "so-fa.jpg",
      rooms: null,
      status: "active",
    },
    productDetail: [
      {
        id: 41,
        code: "PDT-00004",
        colors: "Hồng",
        numberStock: 198,
        productPrice: 16400000.0,
        realPrice: 16400000.0,
        status: "active",
        product: null,
        images: [
          {
            id: 181,
            code: "IM-00019",
            link: "NARBONNE_Sofa_with_chaise_lounge_BAYA_4771_1.jpg",
            productDetail: null,
          },
          {
            id: 191,
            code: "IM-00020",
            link: "NARBONNE_Sofa_with_chaise_lounge_BAYA_4771_2.jpg",
            productDetail: null,
          },
          {
            id: 201,
            code: "IM-00021",
            link: "NARBONNE_Sofa_with_chaise_lounge_BAYA_4771_3.jpg",
            productDetail: null,
          },
          {
            id: 211,
            code: "IM-00022",
            link: "NARBONNE_Sofa_with_chaise_lounge_BAYA_4771_4.jpg",
            productDetail: null,
          },
          {
            id: 221,
            code: "IM-00023",
            link: "NARBONNE_Sofa_with_chaise_lounge_BAYA_4771_5.jpg",
            productDetail: null,
          },
          {
            id: 231,
            code: "IM-00024",
            link: "NARBONNE_Sofa_with_chaise_lounge_BAYA_4771_6.jpg",
            productDetail: null,
          },
        ],
      },
    ],
  },
  {
    id: 41,
    code: "PD-00005",
    name: "Sofa ANTHONY",
    material: "Gỗ/Ván ép/Vải tổng hợp",
    source: "Việt Nam",
    guarantee: 12,
    size: "D83xW193xH83",
    description: null,
    status: "stop",
    productType: {
      id: 61,
      idRooms: null,
      code: "PT-00007",
      name: "Sofa",
      image: "so-fa.jpg",
      rooms: null,
      status: "active",
    },
    productDetail: [
      {
        id: 51,
        code: "PDT-0005",
        colors: "Xám",
        numberStock: 200,
        productPrice: 8990000.0,
        realPrice: 8990000.0,
        status: "stop",
        product: null,
        images: [],
      },
      {
        id: 61,
        code: "PDT-s00006",
        colors: "Be",
        numberStock: 200,
        productPrice: 8990000.0,
        realPrice: 8990000.0,
        status: "stop",
        product: null,
        images: [],
      },
      {
        id: 71,
        code: "PDT-00007",
        colors: "Tím đậm",
        numberStock: 200,
        productPrice: 8990000.0,
        realPrice: 8990000.0,
        status: "stop",
        product: null,
        images: [],
      },
    ],
  },
  {
    id: 51,
    code: "PD-00006",
    name: "Sofa giường JONAS",
    material: "Gỗ/Ván ép/Vải tổng hợp",
    source: "Việt Nam",
    guarantee: 12,
    size: "D86/110xW190xH85/42",
    description: null,
    status: "stop",
    productType: {
      id: 61,
      idRooms: null,
      code: "PT-00007",
      name: "Sofa",
      image: "so-fa.jpg",
      rooms: null,
      status: "active",
    },
    productDetail: [
      {
        id: 81,
        code: "PDT-000008",
        colors: "Xám",
        numberStock: 200,
        productPrice: 7490000.0,
        realPrice: 7490000.0,
        status: "stop",
        product: null,
        images: [],
      },
      {
        id: 91,
        code: "PDT-00009",
        colors: "Orange-Dark-Blue",
        numberStock: 200,
        productPrice: 7490000.0,
        realPrice: 7490000.0,
        status: "stop",
        product: null,
        images: [],
      },
    ],
  },
  {
    id: 61,
    code: "PD-00007",
    name: "Sofa giường có hộc SAMWELL",
    material: "Gỗ/Ván ép/Vải tổng hơp",
    source: "Việt Nam",
    guarantee: 12,
    size: "D86/110xW200xH85/45",
    description: null,
    status: "stop",
    productType: {
      id: 61,
      idRooms: null,
      code: "PT-00007",
      name: "Sofa",
      image: "so-fa.jpg",
      rooms: null,
      status: "active",
    },
    productDetail: [
      {
        id: 101,
        code: "PDT-00010",
        colors: "Hồng",
        numberStock: 200,
        productPrice: 9990000.0,
        realPrice: 9990000.0,
        status: "stop",
        product: null,
        images: [],
      },
      {
        id: 111,
        code: "PDT-00011",
        colors: "Xanh đậm",
        numberStock: 200,
        productPrice: 9990000.0,
        realPrice: 9990000.0,
        status: "stop",
        product: null,
        images: [],
      },
    ],
  },
  {
    id: 71,
    code: "PD-00008",
    name: "Sofa CONNEMARA",
    material: "Vải tổng hợp",
    source: "Việt Nam",
    guarantee: 12,
    size: "D90xW220xH40/82",
    description: null,
    status: "stop",
    productType: {
      id: 61,
      idRooms: null,
      code: "PT-00007",
      name: "Sofa",
      image: "so-fa.jpg",
      rooms: null,
      status: "active",
    },
    productDetail: [
      {
        id: 121,
        code: "PDT-00012",
        colors: "Xanh",
        numberStock: 200,
        productPrice: 14400000.0,
        realPrice: 14400000.0,
        status: "stop",
        product: null,
        images: [],
      },
      {
        id: 131,
        code: "PDT-00013",
        colors: "Be",
        numberStock: 200,
        productPrice: 144000.0,
        realPrice: 144000.0,
        status: "stop",
        product: null,
        images: [],
      },
      {
        id: 141,
        code: "PDT-00014",
        colors: "Xám",
        numberStock: 200,
        productPrice: 14400000.0,
        realPrice: 14400000.0,
        status: "stop",
        product: null,
        images: [],
      },
    ],
  },
];
